name: Check PR title
#on: [push]
on:
  pull_request:
  branches: ['master', 'develop']
  types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}

      - name: Print Title of PR
        run: echo The Title of your PR is ${{ github.context.payload.pull_request.title }}

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@v1.0.7